load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude-replay//python:toolchain.bzl", "standalone_python")

system_genrule_toolchain(
    name="genrule",
    visibility=["PUBLIC"],
)

standalone_python(
    name="python",
    interpreter=select(
        {
            "@prelude//os:windows": "python.exe",
            "DEFAULT": "python3",
        }
    ),
    archive="@prelude-replay//python:python-standalone-archive",
    visibility=["PUBLIC"],
)
