http_archive(
    name="python-standalone-archive",
    # TODO(dmiller): self host this
    urls=select(
        {
            "@prelude//os:macos": select(
                {
                    "@prelude//cpu:arm64": [
                        "https://github.com/indygreg/python-build-standalone/releases/download/20240224/cpython-3.11.8+20240224-aarch64-apple-darwin-pgo-full.tar.zst",
                    ],
                    "@prelude//cpu:x86_64": [
                        "https://github.com/indygreg/python-build-standalone/releases/download/20240224/cpython-3.11.8+20240224-x86_64-apple-darwin-pgo-full.tar.zst",
                    ],
                }
            ),
            "@prelude//os:linux": [
                "https://github.com/indygreg/python-build-standalone/releases/download/20240224/cpython-3.11.8+20240224-x86_64-unknown-linux-gnu-pgo-full.tar.zst",
            ],
            "@prelude//os:windows": [
                "https://github.com/indygreg/python-build-standalone/releases/download/20240224/cpython-3.11.8+20240224-x86_64-pc-windows-msvc-shared-pgo-full.tar.zst",
            ],
        }
    ),
    sha256=select(
        {
            "@prelude//os:macos": select(
                {
                    "@prelude//cpu:arm64": "df7d8f3012dc653eed9e1b5f98d5f623093594dae5d88ea600f6d66fb9421937",
                    "@prelude//cpu:x86_64": "aa1fa172d22bed284350b1d95653358826b4bc560745eb2ab153b69db7356e28",
                }
            ),
            "@prelude//os:linux": "812b818571d2edc097ed67dd0087a9d9754afcb9aebcb8643fc73be34ce2cbfe",
            "@prelude//os:windows": "6da82390f7ac49f6c4b19a5b8019c4ddc1eef2c5ad6a2f2d32773a27663a4e14",
        }
    ),
    visibility=["PUBLIC"],
)

prebuilt_cxx_library(
    name="python-headers",
    header_dirs=["@toolchains//python:python-standalone[includes]"],
    visibility=["PUBLIC"],
)
